apiVersion: v1
kind: Pod
metadata:
 name: node-server-1
 labels:
   app: node-server-1
spec:
 containers:
   - name: node-server-1
     image: pyshif/node-server
     ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
 name: node-server-2
 labels:
   app: node-server-2
spec:
 containers:
   - name: node-server-2
     image: pyshif/node-server
     ports:
       - containerPort: 8080