apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"deployment-label"},"name":"hello-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"pod-label"}},"template":{"metadata":{"labels":{"app":"pod-label"}},"spec":{"containers":[{"image":"pyshif/hello-kubernetes","name":"hello-deployment","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2023-05-23T18:08:28Z"
  generation: 1
  labels:
    app: deployment-label
  name: hello-deployment
  namespace: default
  resourceVersion: "22098"
  uid: f328eb35-e2d4-44e7-a3ee-4dd9cd4c3726
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pod-label
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod-label
    spec:
      containers:
      - image: pyshif/hello-kubernetes
        imagePullPolicy: Always
        name: hello-deployment
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-05-23T18:08:34Z"
    lastUpdateTime: "2023-05-23T18:08:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-05-23T18:08:28Z"
    lastUpdateTime: "2023-05-23T18:08:34Z"
    message: ReplicaSet "hello-deployment-7c58d4dfff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
