apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"deployment-label"},"name":"hello-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"pod-label"}},"template":{"metadata":{"labels":{"app":"pod-label"}},"spec":{"containers":[{"image":"pyshif/hello-kubernetes","name":"hello-pod","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2023-05-23T17:01:09Z"
  generation: 2
  labels:
    app: deployment-label
  name: hello-deployment
  namespace: default
  resourceVersion: "19339"
  uid: 904b8d36-241c-4912-bd30-e833a68acf02
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pod-label
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod-label
    spec:
      containers:
      - image: pyshif/hello-kubernetes
        imagePullPolicy: Always
        name: hello-pod
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2023-05-23T17:01:09Z"
    lastUpdateTime: "2023-05-23T17:01:15Z"
    message: ReplicaSet "hello-deployment-6f58bc5cdc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-23T17:14:48Z"
    lastUpdateTime: "2023-05-23T17:14:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
