apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2023-05-23T18:27:05Z"
  name: hello-deployment
  namespace: default
  resourceVersion: "23048"
  uid: 92f6f61a-5940-4679-802f-2f03dedc1fcc
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-deployment
status:
  conditions:
  - lastTransitionTime: "2023-05-23T18:27:20Z"
    message: the HPA controller was able to get the target's current scale
    reason: SucceededGetScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2023-05-23T18:27:20Z"
    message: 'the HPA was unable to compute the replica count: failed to get cpu utilization:
      missing request for cpu in container hello-deployment of Pod hello-deployment-7c58d4dfff-8vnmw'
    reason: FailedGetResourceMetric
    status: "False"
    type: ScalingActive
  currentMetrics: null
  currentReplicas: 2
  desiredReplicas: 0
