apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-23T17:04:39Z"
  labels:
    app: deployment-label
  name: hello-deployment
  namespace: default
  resourceVersion: "18806"
  uid: 6596ea67-2491-47c7-896c-6c09ee65e0d0
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.251.50
  clusterIPs:
  - 10.102.251.50
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32446
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pod-label
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1
