// service.yaml
apiVersion: v1
kind: Service
metadata:
  name: node-server-service
spec:
  selector:
    type: demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
