apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: deployment-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-label
  template:
    metadata:
      labels:
        app: pod-label
    spec:
      containers:
      - name: hello-deployment
        image: pyshif/hello-kubernetes
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 500Mi